Fix Stack overflow crash when angelica is loaded ...
by disabling some methods from GLDebug class from angelica
```
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 14/11/24 14:50
Description: Unexpected error

java.lang.RuntimeException: Stack overflow
	at com.gtnewhorizons.angelica.glsm.GLDebug$KHRDebugState.pushGroup(GLDebug.java:298)
	at com.gtnewhorizons.angelica.glsm.GLDebug.pushGroup(GLDebug.java:365)
	at net.minecraft.profiler.Profiler.handler$zzn000$angelica$debugStartSection(SourceFile:514)
	at net.minecraft.profiler.Profiler.func_76320_a(SourceFile)
	at net.minecraft.world.World.func_72939_s(World.java:1795)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:2006)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:898)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at com.gtnewhorizons.angelica.glsm.GLDebug$KHRDebugState.pushGroup(GLDebug.java:298)
	at com.gtnewhorizons.angelica.glsm.GLDebug.pushGroup(GLDebug.java:365)
	at net.minecraft.profiler.Profiler.handler$zzn000$angelica$debugStartSection(SourceFile:514)
	at net.minecraft.profiler.Profiler.func_76320_a(SourceFile)
	at net.minecraft.world.World.func_72939_s(World.java:1795)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityClientPlayerMP['Quentin453'/378, l='MpServer', x=49496.91, y=6.62, z=-76.56]]
	Chunk stats: MultiplayerChunkCache: 115, 115
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options:
	Level spawn location: World: (80,64,240), Chunk: (at 0,4,0 in 5,15; contains blocks 80,0,240 to 95,255,255), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 57853 game time, 57853 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 102 total; [EntityZombie['Zombie'/515, l='MpServer', x=49421.50, y=4.00, z=-44.50], EntityZombie['Zombie'/516, l='MpServer', x=49420.50, y=4.00, z=-43.50], EntitySkeleton['Squelette'/517, l='MpServer', x=49417.50, y=4.00, z=-99.50], EntityMinecartChest['entity.MinecartChest.name'/526, l='MpServer', x=49540.50, y=28.50, z=-156.50], EntityClientPlayerMP['Quentin453'/378, l='MpServer', x=49496.91, y=6.62, z=-76.56], EntityBat['Chauve-souris'/379, l='MpServer', x=49500.69, y=9.10, z=-78.56], EntitySlime['Slime'/380, l='MpServer', x=49497.20, y=5.96, z=-74.50], EntitySpider['Araignée'/381, l='MpServer', x=49473.38, y=5.00, z=-70.66], EntityZombie['Zombie'/382, l='MpServer', x=49519.94, y=14.00, z=-73.50], EntitySquid['Poulpe'/383, l='MpServer', x=49522.73, y=32.79, z=-71.60], EntitySkeleton['Squelette'/384, l='MpServer', x=49533.50, y=12.00, z=-99.50], EntitySquid['Poulpe'/385, l='MpServer', x=49444.85, y=53.62, z=-65.64], EntitySquid['Poulpe'/386, l='MpServer', x=49498.41, y=58.28, z=-19.66], EntitySquid['Poulpe'/387, l='MpServer', x=49501.47, y=57.38, z=-26.63], EntitySquid['Poulpe'/388, l='MpServer', x=49496.34, y=59.34, z=-28.03], EntitySquid['Poulpe'/389, l='MpServer', x=49502.50, y=58.72, z=-25.66], EntitySquid['Poulpe'/390, l='MpServer', x=49503.63, y=59.19, z=-21.34], EntityCreeper['Creeper'/391, l='MpServer', x=49487.16, y=13.00, z=-23.13], EntitySquid['Poulpe'/392, l='MpServer', x=49443.13, y=59.97, z=-54.84], EntitySquid['Poulpe'/393, l='MpServer', x=49451.94, y=59.38, z=-60.28], EntitySquid['Poulpe'/394, l='MpServer', x=49443.47, y=60.97, z=-58.91], EntitySquid['Poulpe'/395, l='MpServer', x=49551.34, y=43.25, z=-53.03], EntityBat['Chauve-souris'/396, l='MpServer', x=49512.31, y=9.10, z=-31.28], EntitySquid['Poulpe'/397, l='MpServer', x=49508.94, y=58.88, z=-23.44], EntitySpider['Araignée'/398, l='MpServer', x=49442.56, y=6.53, z=-37.72], EntitySpider['Araignée'/399, l='MpServer', x=49444.97, y=11.00, z=-36.75], EntitySquid['Poulpe'/400, l='MpServer', x=49452.19, y=58.38, z=-37.06], EntitySquid['Poulpe'/401, l='MpServer', x=49449.88, y=61.06, z=-34.09], EntitySquid['Poulpe'/402, l='MpServer', x=49548.63, y=54.34, z=-102.81], EntitySquid['Poulpe'/403, l='MpServer', x=49547.68, y=39.96, z=-47.77], EntitySquid['Poulpe'/404, l='MpServer', x=49541.59, y=54.97, z=-47.47], EntitySquid['Poulpe'/405, l='MpServer', x=49550.44, y=48.16, z=-36.50], EntitySquid['Poulpe'/406, l='MpServer', x=49534.34, y=51.09, z=-16.09], EntitySquid['Poulpe'/407, l='MpServer', x=49535.59, y=51.69, z=-17.75], EntitySquid['Poulpe'/408, l='MpServer', x=49503.31, y=42.31, z=-140.56], EntitySquid['Poulpe'/409, l='MpServer', x=49501.63, y=47.91, z=-139.09], EntitySquid['Poulpe'/411, l='MpServer', x=49496.94, y=52.31, z=-135.09], EntitySquid['Poulpe'/412, l='MpServer', x=49493.19, y=50.28, z=-135.31], EntitySquid['Poulpe'/413, l='MpServer', x=49502.97, y=53.38, z=-132.53], EntitySquid['Poulpe'/414, l='MpServer', x=49491.78, y=51.34, z=-135.06], EntitySquid['Poulpe'/415, l='MpServer', x=49492.94, y=52.38, z=-136.31], EntitySquid['Poulpe'/416, l='MpServer', x=49500.31, y=55.38, z=-140.50], EntitySquid['Poulpe'/419, l='MpServer', x=49559.66, y=42.97, z=-66.56], EntitySquid['Poulpe'/420, l='MpServer', x=49557.97, y=45.91, z=-73.75], EntitySquid['Poulpe'/423, l='MpServer', x=49556.38, y=48.34, z=-75.47], EntitySpider['Araignée'/426, l='MpServer', x=49498.50, y=5.00, z=-2.50], EntitySpider['Araignée'/427, l='MpServer', x=49499.50, y=5.00, z=-0.50], EntityZombie['Zombie'/428, l='MpServer', x=49500.50, y=5.00, z=-1.50], EntityZombie['Zombie'/429, l='MpServer', x=49499.50, y=5.00, z=-2.50], EntityZombie['Zombie'/430, l='MpServer', x=49496.50, y=5.00, z=-0.50], EntityBat['Chauve-souris'/431, l='MpServer', x=49426.50, y=13.10, z=-56.50], EntitySpider['Araignée'/432, l='MpServer', x=49424.50, y=4.00, z=-55.50], EntityZombie['Zombie'/433, l='MpServer', x=49432.38, y=4.00, z=-48.91], EntityZombie['Zombie'/434, l='MpServer', x=49427.50, y=4.00, z=-49.50], EntitySquid['Poulpe'/435, l='MpServer', x=49436.59, y=57.34, z=-50.53], EntitySquid['Poulpe'/436, l='MpServer', x=49433.34, y=57.28, z=-51.53], EntitySkeleton['Squelette'/437, l='MpServer', x=49428.01, y=4.00, z=-90.99], EntityCreeper['Creeper'/438, l='MpServer', x=49426.50, y=4.00, z=-94.50], EntitySquid['Poulpe'/444, l='MpServer', x=49480.03, y=54.25, z=-136.47], EntityWitch['Sorcière'/445, l='MpServer', x=49511.50, y=10.00, z=-134.50], EntityMinecartChest['entity.MinecartChest.name'/446, l='MpServer', x=49517.50, y=28.50, z=-143.50], EntitySquid['Poulpe'/447, l='MpServer', x=49509.03, y=49.31, z=-133.63], EntitySquid['Poulpe'/448, l='MpServer', x=49515.81, y=51.28, z=-137.72], EntitySquid['Poulpe'/450, l='MpServer', x=49505.13, y=49.78, z=-131.59], EntitySquid['Poulpe'/452, l='MpServer', x=49558.09, y=50.31, z=-84.91], EntitySquid['Poulpe'/453, l='MpServer', x=49560.16, y=48.91, z=-80.78], EntitySquid['Poulpe'/454, l='MpServer', x=49557.19, y=48.72, z=-87.06], EntitySquid['Poulpe'/455, l='MpServer', x=49555.56, y=46.34, z=-59.03], EntitySquid['Poulpe'/456, l='MpServer', x=49557.63, y=46.88, z=-52.09], EntitySquid['Poulpe'/458, l='MpServer', x=49555.78, y=46.13, z=-60.19], EntitySquid['Poulpe'/459, l='MpServer', x=49554.19, y=45.97, z=-63.22], EntitySquid['Poulpe'/460, l='MpServer', x=49558.16, y=43.38, z=-63.84], EntitySquid['Poulpe'/462, l='MpServer', x=49555.81, y=52.03, z=-52.25], EntityZombie['Zombie'/463, l='MpServer', x=49504.50, y=5.00, z=-1.50], EntityCreeper['Creeper'/464, l='MpServer', x=49510.50, y=14.00, z=-8.50], EntityBat['Chauve-souris'/465, l='MpServer', x=49440.32, y=4.00, z=-27.25], EntitySpider['Araignée'/466, l='MpServer', x=49442.50, y=10.00, z=-30.50], EntitySkeleton['Squelette'/467, l='MpServer', x=49455.50, y=8.44, z=-125.50], EntityCreeper['Creeper'/468, l='MpServer', x=49449.16, y=12.00, z=-116.91], EntitySquid['Poulpe'/469, l='MpServer', x=49438.84, y=52.25, z=-42.19], EntitySquid['Poulpe'/472, l='MpServer', x=49470.63, y=41.34, z=-137.44], EntitySquid['Poulpe'/473, l='MpServer', x=49558.75, y=54.34, z=-103.66], EntitySquid['Poulpe'/474, l='MpServer', x=49560.09, y=49.66, z=-104.44], EntitySquid['Poulpe'/475, l='MpServer', x=49556.16, y=52.38, z=-107.69], EntitySquid['Poulpe'/476, l='MpServer', x=49554.13, y=49.03, z=-46.50], EntityBat['Chauve-souris'/479, l='MpServer', x=49452.28, y=7.90, z=-2.69], EntityZombie['Zombie'/480, l='MpServer', x=49441.50, y=14.00, z=-133.50], EntitySquid['Poulpe'/489, l='MpServer', x=49542.91, y=43.84, z=-131.91], EntitySquid['Poulpe'/490, l='MpServer', x=49545.09, y=39.28, z=-139.31], EntitySkeleton['Squelette'/491, l='MpServer', x=49541.50, y=12.00, z=-2.50], EntitySquid['Poulpe'/493, l='MpServer', x=49536.78, y=54.38, z=-15.16], EntitySpider['Araignée'/495, l='MpServer', x=49496.50, y=5.00, z=0.50], EntityZombie['Zombie'/500, l='MpServer', x=49500.50, y=4.00, z=1.50], EntityZombie['Zombie'/501, l='MpServer', x=49497.50, y=4.00, z=1.50], EntitySpider['Araignée'/503, l='MpServer', x=49420.50, y=4.00, z=-54.50], EntityZombie['Zombie'/504, l='MpServer', x=49422.50, y=5.32, z=-53.50], EntitySpider['Araignée'/505, l='MpServer', x=49419.50, y=4.00, z=-94.50], EntitySpider['Araignée'/506, l='MpServer', x=49422.50, y=4.00, z=-90.50], EntityCreeper['Creeper'/507, l='MpServer', x=49421.50, y=4.00, z=-90.50], EntitySkeleton['Squelette'/508, l='MpServer', x=49423.50, y=4.00, z=-94.50], EntitySkeleton['Squelette'/510, l='MpServer', x=49508.50, y=13.00, z=-152.50], EntityBat['Chauve-souris'/511, l='MpServer', x=49517.63, y=29.10, z=-152.13]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:373)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2444)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:927)
	at net.minecraft.client.main.Main.main(SourceFile:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_432, Azul Systems, Inc.
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Azul Systems, Inc.
	Memory: 332595928 bytes (317 MB) / 607125504 bytes (579 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 4 total; -Xmx4096m -Xms4096m -Xms128m -XX:+UseG1GC
	AABB Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP v9.05 FML v7.10.99.99 Minecraft Forge 10.13.4.1614 46 mods loaded, 46 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.05} [Minecraft Coder Pack] (minecraft.jar)
	UCHIJAAAA	FML{7.10.99.99} [Forge Mod Loader] (forge-1.7.10-10.13.4.1614-1.7.10.jar)
	UCHIJAAAA	Forge{10.13.4.1614} [Minecraft Forge] (forge-1.7.10-10.13.4.1614-1.7.10.jar)
	UCHIJAAAA	CartFixes{0.1.0} [Steve's Cart Fixes] (minecraft.jar)
	UCHIJAAAA	CodeChickenCore{1.3.10} [CodeChicken Core] (minecraft.jar)
	UCHIJAAAA	InputFix{1.7.10-v6} [InputFix] (minecraft.jar)
	UCHIJAAAA	NotEnoughItems{2.6.44-GTNH} [NotEnoughItems] (NotEnoughItems-2.6.44-GTNH.jar)
	UCHIJAAAA	GTNHLib Core{0.5.20} [GTNHLib Core] (minecraft.jar)
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar)
	UCHIJAAAA	FoamFixCore{1.0.4} [FoamFixCore] (minecraft.jar)
	UCHIJAAAA	unimixins{0.1.19} [UniMixins] (+unimixins-all-1.7.10-0.1.19.jar)
	UCHIJAAAA	unimixins-mixin{0.1.19} [UniMixins: Mixin (UniMix)] (+unimixins-all-1.7.10-0.1.19.jar)
	UCHIJAAAA	unimixins-compat{0.1.19} [UniMixins: Compatibility] (+unimixins-all-1.7.10-0.1.19.jar)
	UCHIJAAAA	mixingasm{0.3} [UniMixins: Mixingasm] (+unimixins-all-1.7.10-0.1.19.jar)
	UCHIJAAAA	spongemixins{2.0.1} [UniMixins: SpongeMixins] (+unimixins-all-1.7.10-0.1.19.jar)
	UCHIJAAAA	mixinbooterlegacy{1.2.1} [UniMixins: MixinBooterLegacy] (+unimixins-all-1.7.10-0.1.19.jar)
	UCHIJAAAA	gasstation{0.5.1} [UniMixins: GasStation] (+unimixins-all-1.7.10-0.1.19.jar)
	UCHIJAAAA	gtnhmixins{2.2.0} [UniMixins: GTNHMixins] (+unimixins-all-1.7.10-0.1.19.jar)
	UCHIJAAAA	mixinextras{0.1.19} [UniMixins: MixinExtras] (+unimixins-all-1.7.10-0.1.19.jar)
	UCHIJAAAA	alreadydecoratingfix{1.0a} [Already Decorating Fix] (alreadydecoratingfix-1.0a.jar)
	UCHIJAAAA	mcpatcherforge{1.0.0-alpha} [MCPatcherForge] (angelica-1.0.0-beta18.jar)
	UCHIJAAAA	notfine{1.0.0-beta18} [NotFine] (angelica-1.0.0-beta18.jar)
	UCHIJAAAA	archaicfix{0.7.0fork8-main.1+eebac5c3d6-dirty} [ArchaicFix] (archaicfix-0.7.0fork8-main.1+eebac5c3d6-dirty.jar)
	UCHIJAAAA	gtnhlib{0.5.20} [GTNH Lib] (gtnhlib-0.5.20.jar)
	UCHIJAAAA	angelica{1.0.0-beta18} [Angelica] (angelica-1.0.0-beta18.jar)
	UCHIJAAAA	embeddium{1.0.0-beta18} [Embeddium] (angelica-1.0.0-beta18.jar)
	UCHIJAAAA	biggerpacketsplz{1.2} [Bigger Packets, please !] (biggerpacketsplz-upto1.7.10-1.2.jar)
	UCHIJAAAA	bugtorch{1.2.13-GTNH} [BugTorch] (bugtorch-1.2.13-GTNH.jar)
	UCHIJAAAA	clearchat{1.1} [ClearChat] (clearchat-1.1.jar)
	UCHIJAAAA	CoFHCore{1.7.10R3.1.4} [CoFH Core] (CoFHCore-[1.7.10]3.1.4-329.jar)
	UCHIJAAAA	evilnotchlib{1.0} [Evil Notch Lib] (evilnotchlib-a109.jar)
	UCHIJAAAA	confighelper{1.2.4.7} [Config Helper] (confighelper-1.7.10-1.2.5.5.jar)
	UCHIJAAAA	controlling{1.7.10-1.0.0.8} [Controlling] (Controlling-1.7.10-1.0.0.8.jar)
	UCHIJAAAA	danger_craft{1.0} [DangerCraft] (danger_craft-1.7.10-v1.0.jar)
	UCHIJAAAA	entityculling{@VER@} [EntityCulling] (entityculling-1.6.4-mc1.7.10.jar)
	UCHIJAAAA	foamfix{@VERSION@} [FoamFix] (FoamFix-1.7.10-universal-1.0.4.jar)
	UCHIJAAAA	FpsReducer{mc1.7.10-1.10.3} [FPS Reducer] (FpsReducer-mc1.7.10-1.10.3.jar)
	UCHIJAAAA	fw{1.3.0} [Fullscreen Windowed] (FullscreenWindowed-1.7.10-1.3.0b.jar)
	UCHIJAAAA	geckolib3{3.0.30} [GeckoLib] (geckolib-unofficial-1.7.10-1.0.3.jar)
	UCHIJAAAA	HelpFixer{1.2.0} [HelpFixer] (HelpFixer-1.2.0.jar)
	UCHIJAAAA	neodymium{0.3.3-unofficial} [Neodymium Unofficial] (neodymium-mc1.7.10-0.3.3-unofficial.jar)
	UCHIJAAAA	optimizationsandtweaks{0.8.7.4.2} [Optimizations and Tweaks] (optimizationsandtweaks-V1.13.9-1-7-10.5+74fda297ed-dirty.jar)
	UCHIJAAAA	OreSpawn{1.7.10.20.3} [OreSpawn] (orespawn-1.7.10-20.3.zip)
	UCHIJAAAA	spark{1.10.35} [spark] (spark-1.10.19-forge1710.jar)
	UCHIJAAAA	Waila{1.7.0} [Waila] (Waila-1.7.0.jar)
	UCHIJAAAA	zoomermod{1.0} [§czoomermod] (Zoomer - Simple Zoom.jar)
	CoFHCore: -[1.7.10]3.1.4-329
	Mixins in Stacktrace:
		net.minecraft.client.Minecraft:
			mixins.archaicfix.early.json:client.core.MixinMinecraft from mod archaicfix
			mixins.archaicfix.early.json:client.lighting.MixinMinecraft from mod archaicfix
			mixins.angelica.early.json:angelica.MixinMinecraft from mod angelica
		net.minecraft.world.World:
			mixins.archaicfix.early.json:common.lighting.MixinWorld_Lighting from mod archaicfix
			mixins.archaicfix.early.json:client.lighting.MixinWorld from mod archaicfix
			mixins.archaicfix.early.json:common.core.MixinWorld from mod archaicfix
		net.minecraft.profiler.Profiler:
			mixins.angelica.early.json:angelica.debug.MixinProfiler from mod angelica
	Launched Version: 1.7.10
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics 620 GL version 4.5.0 - Build 23.20.16.4936, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Anisotropic filtering is supported and maximum anisotropy is 16.
Shaders are available because OpenGL 2.1 is supported.

	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: []
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	Vec3 Pool Size: 0 (0 bytes; 0 MB) allocated, 0 (0 bytes; 0 MB) used
	Anisotropic Filtering: Off (1)
```